### ISSUE TITLE
the generated chromap tool command line from seqspec index should probably use filenames instead of read ids

### ISSUE THREAD

**Issue by detrout** [pachterlab/seqspec#64]
I found a seqspec behavior I think should be considered incorrect. When generating a chromap command line with read ids that are just the accession because there's a file: filename: field with the filename with exension the read ids are used for the fastq names instead of the filename. 

Given a seqspec that contains blocks like this:

```
- !Read
  read_id: IGVFFI3729HEZB
  name: Index 1 (i7 index)
  modality: atac
  primer_id: atac-truseq_read2
  min_len: 99
  max_len: 99
  strand: pos
  files:
  - !File
    file_id: IGVFFI3729HEZB
    filename: IGVFFI3729HEZB.fastq.gz
    filetype: fastq
    filesize: 15144535353
    url: https://api.data.igvf.org/sequence-files/IGVFFI3729HEZB/@@download/IGVFFI3729HEZB.fastq.gz
    urltype: https
    md5: ec773ee60f03d8727c8b9ae732b7b06c
```

I get a chromap command line like this:

```'-1 IGVFFI0673YIFA -2 IGVFFI3998EXGB --barcode IGVFFI3729HEZB --read-format bc:15:22,bc:53:60,bc:91:98,r1:0:49,r2:0:49'```

But I think the command has access to enough information to find the filename in the file block and return this string instead

```'-1 IGVFFI0673YIFA.fastq.gz -2 IGVFFI3998EXGB.fastq.gz --barcode IGVFFI3729HEZB.fastq.gz --read-format bc:15:22,bc:53:60,bc:91:98,r1:0:49,r2:0:49'```

It's possible to work around the issue by making your read id the same as your filename, but then the filename is redundant.

**Comment by detrout** [comment]
And here's the full seqspec.

```
!Assay
seqspec_version: 0.3.0
assay_id: share-seq-atac
name: SHARE-seq ATAC
doi: https://doi.org/10.1016/j.cell.2020.09.056
date: 23 October 2020
description: ATAC reads from simultaneous high-throughput ATAC and RNA expression
modalities:
- atac
lib_struct: https://teichlab.github.io/scg_lib_structs/methods_html/SHARE-seq.html
library_protocol: single-nucleus RNA sequencing assay (OBI:0003109)
library_kit: Illumina Truseq Dual Index
sequence_protocol: Illumina NextSeq 2000 (EFO:0010963)
sequence_kit: NextSeq 2000 P4 XLEAP-SBS Reagent Kit
sequence_spec:
- !Read
  read_id: IGVFFI3729HEZB
  name: Index 1 (i7 index)
  modality: atac
  primer_id: atac-truseq_read2
  min_len: 99
  max_len: 99
  strand: pos
  files:
  - !File
    file_id: IGVFFI3729HEZB
    filename: IGVFFI3729HEZB.fastq.gz
    filetype: fastq
    filesize: 15144535353
    url: https://api.data.igvf.org/sequence-files/IGVFFI3729HEZB/@@download/IGVFFI3729HEZB.fastq.gz
    urltype: https
    md5: ec773ee60f03d8727c8b9ae732b7b06c
- !Read
  read_id: IGVFFI0673YIFA
  name: Read 1
  modality: atac
  primer_id: atac-truseq_read1
  min_len: 50
  max_len: 50
  strand: pos
  files:
  - !File
    file_id: IGVFFI0673YIFA
    filename: IGVFFI0673YIFA.fastq.gz
    filetype: fastq
    filesize: 21640730143
    url: https://api.data.igvf.org/sequence-files/IGVFFI0673YIFA/@@download/IGVFFI0673YIFA.fastq.gz
    urltype: https
    md5: 0dcde748da00e93770caad9fb0320b45
- !Read
  read_id: IGVFFI3998EXGB
  name: Read 2
  modality: atac
  primer_id: atac-truseq_read2
  min_len: 50
  max_len: 50
  strand: neg
  files:
  - !File
    file_id: IGVFFI3998EXGB
    filename: IGVFFI3998EXGB.fastq.gz
    filetype: fastq
    filesize: 22593508239
    url: https://api.data.igvf.org/sequence-files/IGVFFI3998EXGB/@@download/IGVFFI3998EXGB.fastq.gz
    urltype: https
    md5: 76a5002354b1b0a7da90c426de19ac59
library_spec:
- !Region
  parent_id: null
  region_id: atac
  region_type: atac
  name: SHARE-seq ATAC
  sequence_type: joined
  sequence: AATGATACGGCGACCACCGAGATCTACACXXXXXXXXXXTCTTTCCCTACACGACGCTCTTCCGATCTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTTCGGACGATCATGGGNNNNNNNNCAAGTATGCAGCGCGCTCAAGCACGTGGATNNNNNNNNAGTCGTACGCCGATGCGAAACATCGGCCACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
  min_len: 325
  max_len: 325
  onlist: null
  regions:
  - !Region
    parent_id: atac
    region_id: atac-illumina_p5
    region_type: illumina_p5
    name: Illumina P5
    sequence_type: fixed
    sequence: AATGATACGGCGACCACCGAGATCTACAC
    min_len: 29
    max_len: 29
    onlist: null
    regions: null
  - !Region
    parent_id: atac
    region_id: atac-index5
    region_type: index5
    name: i5 index
    sequence_type: random
    sequence: XXXXXXXXXX
    min_len: 10
    max_len: 10
    onlist: null
    regions: null
  - !Region
    parent_id: atac
    region_id: atac-truseq_read1
    region_type: truseq_read1
    name: ATAC Truseq Read 1
    sequence_type: fixed
    sequence: TCTTTCCCTACACGACGCTCTTCCGATCT
    min_len: 29
    max_len: 29
    onlist: null
    regions: null
  - !Region
    parent_id: atac
    region_id: atac-gdna
    region_type: gdna
    name: ATAC genomic DNA
    sequence_type: random
    sequence: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    min_len: 100
    max_len: 100
    onlist: null
    regions: null
  - !Region
    parent_id: atac
    region_id: atac-truseq_read2
    region_type: truseq_read2
    name: Truseq Read 2
    sequence_type: fixed
    sequence: GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
    min_len: 34
    max_len: 34
    onlist: null
    regions: null
  - !Region
    region_id: IGVFFI3729HEZB_I1
    region_type: named
    name: atac Raw Cell Barcode
    sequence_type: joined
    sequence: TCGGACGATCATGGGNNNNNNNNCAAGTATGCAGCGCGCTCAAGCACGTGGATNNNNNNNNAGTCGTACGCCGATGCGAAACATCGGCCACNNNNNNNN
    min_len: 99
    max_len: 99
    onlist: null
    parent_id: atac
    regions:
    - !Region
      region_id: atac-linker1
      region_type: linker
      name: linker1
      sequence_type: fixed
      sequence: TCGGACGATCATGGG
      min_len: 15
      max_len: 15
      onlist: null
      regions: null
      parent_id: IGVFFI3729HEZB_I1
    - !Region
      region_id: atac-cell-barcode1
      region_type: barcode
      name: atac Cell Barcode 1
      sequence_type: onlist
      sequence: NNNNNNNN
      min_len: 8
      max_len: 8
      onlist: !Onlist
        file_id: IGVFFI2668ZFEB
        filename: IGVFFI2668ZFEB.tsv.gz
        filetype: tsv
        filesize: 329
        location: remote
        url: https://data.igvf.org/tabular-files/IGVFFI2668ZFEB/@@download/IGVFFI2668ZFEB.tsv.gz
        urltype: https
        md5: 073f131a4a831ad2fdfe981e8f7a86b5
      regions: null
      parent_id: IGVFFI3729HEZB_I1
    - !Region
      region_id: atac-linker2
      region_type: linker
      name: linker2
      sequence_type: fixed
      sequence: CAAGTATGCAGCGCGCTCAAGCACGTGGAT
      min_len: 30
      max_len: 30
      onlist: null
      regions: null
      parent_id: IGVFFI3729HEZB_I1
    - !Region
      region_id: atac-cell-barcode2
      region_type: barcode
      name: atac Cell Barcode 2
      sequence_type: onlist
      sequence: NNNNNNNN
      min_len: 8
      max_len: 8
      onlist: !Onlist
        file_id: IGVFFI2668ZFEB
        filename: IGVFFI2668ZFEB.tsv.gz
        filetype: tsv
        filesize: 329
        location: remote
        url: https://data.igvf.org/tabular-files/IGVFFI2668ZFEB/@@download/IGVFFI2668ZFEB.tsv.gz
        urltype: https
        md5: 073f131a4a831ad2fdfe981e8f7a86b5
      regions: null
      parent_id: IGVFFI3729HEZB_I1
    - !Region
      region_id: atac-linker3
      region_type: linker
      name: linker3
      sequence_type: fixed
      sequence: AGTCGTACGCCGATGCGAAACATCGGCCAC
      min_len: 30
      max_len: 30
      onlist: null
      regions: null
      parent_id: IGVFFI3729HEZB_I1
    - !Region
      region_id: atac-cell-barcode3
      region_type: barcode
      name: atac Cell Barcode 3
      sequence_type: onlist
      sequence: NNNNNNNN
      min_len: 8
      max_len: 8
      onlist: !Onlist
        file_id: IGVFFI2668ZFEB
        filename: IGVFFI2668ZFEB.tsv.gz
        filetype: tsv
        filesize: 329
        location: remote
        url: https://data.igvf.org/tabular-files/IGVFFI2668ZFEB/@@download/IGVFFI2668ZFEB.tsv.gz
        urltype: https
        md5: 073f131a4a831ad2fdfe981e8f7a86b5
      regions: null
      parent_id: IGVFFI3729HEZB_I1
  - !Region
    parent_id: atac
    region_id: atac-illumina_p7
    region_type: illumina_p7
    name: Illumina P7
    sequence_type: fixed
    sequence: ATCTCGTATGCCGTCTTCTGCTTG
    min_len: 24
    max_len: 24
    onlist: null
    regions: null
```
